--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/boymelancholy/apiitem
build-by-default: true
branches:
- master
projects:
  apiitem:
    path: ""
    model: virion
    type: library
...
